---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tube-archivist.fullname" . }}-cache
  labels:
    {{- include "tube-archivist.labels" . | nindent 4 }}
   
  {{- with .Values.persistence.youtube.annotations }} 
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.cache.size | quote }}
  {{- with .Values.persistence.cache.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tube-archivist.fullname" . }}-youtube
  labels:
    {{- include "tube-archivist.labels" . | nindent 4 }}
  {{- with .Values.persistence.youtube.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.youtube.size | quote }}
  {{- with .Values.persistence.youtube.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
