apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tube-archivist.fullname" . }}-pot-provider
  labels:
    {{- include "tube-archivist.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      {{- include "tube-archivist.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tube-archivist.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: pot-provider
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tube-archivist.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.potProvider.image.repository }}:{{ .Values.potProvider.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.potProvider.image.pullPolicy }}
          {{- with .Values.env }}
          env: 
            {{- toYaml . | nindent 12 -}}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.potProvider.service.port }}
              protocol: TCP
          {{- with .Values.potProvider.startupProbe }}
          startupProbe:
            {{- toYaml .  | nindent 12 }}
          {{- end -}}
          {{- with .Values.potProvider.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.potProvider.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.potProvider.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
